#!/usr/bin/env python3

import sys

# arg 1: filename
# arg 2: interconne value
if __name__ == "__main__":
    if len(sys.argv) < 3:
        exit(1)

    filename = sys.argv[1]
    param = sys.argv[2]

    for line in sys.stdin:
        line = line.strip()
        if len(line) == 0:
            continue
        tokens = line.split(",")
        detection = tokens[9].strip()
        interconn = tokens[10].strip()
        if detection == "" or interconn == "":
            continue
        if interconn.lower() == param.lower():
            print(f"{detection}:1")
